#!/bin/sh

# Accelerator for CTranslate2
brew install onednn
brew install icu4c

# Download M2M-100 model
wget -P models/ https://cdn.argosopentech.io/translate-fairseq_m2m_100_418M.argosmodel
unzip models/translate-fairseq_m2m_100_418M.argosmodel -d models/

